name: 255 Pull Request Workflow
on:
  pull_request:
    branches:
      - tb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
